pub global OP_0: u8 = 0;

pub global OP_PUSHBYTES1: u8 = 1;
pub global OP_PUSHBYTES75: u8 = 75;

pub global OP_PUSHDATA1: u8 = 76;
pub global OP_PUSHDATA2: u8 = 77;
pub global OP_PUSHDATA4: u8 = 78;

pub global OP_1NEGATE: u8 = 79;
pub global OP_1: u8 = 81;
pub global OP_16: u8 = 96;

pub global OP_DUP: u8 = 118;

pub global OP_HASH160: u8 = 169;

pub global OP_EQUAL: u8 = 135;
pub global OP_EQUALVERIFY: u8 = 136;

pub global OP_CHECKSIG: u8 = 172;
pub global OP_CHECKSIGVERIFY: u8 = 173;
